version: '3.7'

services:
  php-apache:
    build: .
    ports:
      - "8000:80"
    volumes:
    - type: volume
      source: dokuwiki_data
      target: /var/www/html/


volumes:
  dokuwiki_data:
    external:
      name: dokuwiki_data

#
