version: '3.7'

services:
  php-apache:
    build: .
    ports:
      - "8000:80"
    volumes:
    - type: volume
      source: macwiki_data
      target: /var/www/html/


volumes:
  macwiki_data:
    external:
      name: macwiki_data
